name = "TestLandscapes"
uuid = "acebfb02-3096-4040-86f5-d41b0f19d497"
authors = ["Gideon Simpson <gideon.simpson@gmail.com>"]
version = "0.1.1"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.5"
StaticArrays = "1.0"
